### ISSUE TITLE
大神，帮忙给每个项目加个简介和Keywords的标签吧

### ISSUE THREAD

**Issue by ghost** [troyguo/awesome-dv#1]
大神，整理得很好！对你的崇拜犹如滔滔江水，连绵不绝。
我决定紧跟大佬脚步，立即学起来。但是，在学习时遇到一些困惑，无法抓住重点。能否帮忙给每个项目加个简介和Keywords的标签吗？
谢谢！

**Comment by troyguo** [comment]
Good suggestion. I will work on it when not busy.
